"""create users and products

Revision ID: 8415bb2ab623
Revises: 
Create Date: 2025-12-29 12:49:24.934142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8415bb2ab623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true() ),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='fk_products_owner_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # op.create_foreign_key(
    #     "fk_products_owner_id_users",
    #     "products",
    #     "users",
    #     ["owner_id"],
    #     ["id"],
    #     ondelete="CASCADE"
    # )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(
    #     "fk_products_owner_id_users",
    #     "products",
    #     type_="foreignkey"
    # )
    op.drop_table('products')
    op.drop_table('users')
    # ### end Alembic commands ###
